---
# tasks file for mysql

- name: Install mysql apt-packages
  apt:
    name: mysql-server
    update_cache: yes
    state: present

- name: copy .my.cnf file with root password
  template:
    src: templates/my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    mode: 0600

#- mysql_user:
#    name: mathieu
#    password: 123
#    priv: '*.*:ALL,GRANT'
#    state: present

#- name: Create a new database with name 'beerbattle'
#  mysql_db:
#    name: beerbattle
#    state: present
#
#- name: Copy database dump file
#  copy:
#    src: dump.sql.bz2
#    dest: /tmp
#
#- name: Restore database
#  mysql_db:
#    name: my_db
#    state: import
#    target: /tmp/dump.sql.bz2