---
# tasks file for mysql

- name: Install mysql apt-packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - mysql-server
    - python-mysqldb

- name: Start MySQL Service
  service:
    name: mysql
    state: started
    enabled: true

#- name: Set MySQL root password
#  mysql_user:
#    login_user: root
#    login_password: ""
#    name: root
#    password: "{{ mysql_root_password }}"

- name: Copy MySQL Credentials
  template:
    src: templates/my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    mode: 0600

#- name: Create a new database with name 'beerbattle'
#  mysql_db:
#    name: beerbattle
#    state: present
#
#- name: Copy database dump file
#  copy:
#    src: dump.sql.bz2
#    dest: /tmp
#
#- name: Restore database
#  mysql_db:
#    name: my_db
#    state: import
#    target: /tmp/dump.sql.bz2