---
# tasks file for nginx

- name: Stop apache
  service:
    state: stopped
    name: apache2

- name: Install Nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

#- name: Remove conf
#  copy:
#    src: helloworld
#    dest: /etc/nginx/sites-available
#    state: absent
#
#- name: Remove symlink
#  file:
#    state: link
#    src: /etc/nginx/sites-available/helloworld
#    dest: /etc/nginx/sites-enabled/helloworld

- name: Restart ngnix
  service:
    state: restarted
    name: nginx