---
# tasks file for nginx

- name: Stop apache
  service:
    state: stopped
    name: apache2

- name: Install Nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: Remove conf
  file:
    state: absent
    path: /etc/nginx/sites-available/default

- name: Remove symlink
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default

- name: Restart ngnix
  service:
    state: restarted
    name: nginx