################################################################################
# > Playbook used to configure databases
#
# @author: <Your Name>
################################################################################
---

# TODO
- name: Configure databases
  hosts: databases
  become: yes

  roles:
    - mysql
    - webapp-database
    - common
    - role: webapp
      webapp_setup_webserver: no