---
# tasks file for uwsgi

- name: Install UWSGI
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - python-pip
    - python-dev

- name: Install virtualenv
  pip:
    name: virtualenv